// JLPT N5 Question Bank
const QB = {

  // ── SECTION 1: 文字・語彙 ─────────────────────────────────────────

  s1q1: [
    { id:'s1q1_1', sentence:'毎朝、<u>山</u>が見えます。', kanji:'山',
      options:['やま','かわ','もり','うみ'], answer:0,
      explanation:'山（やま）= mountain',
      explanationZh:'山 讀作 やま，意思是「山」。' },
    { id:'s1q1_2', sentence:'あの<u>川</u>はとても長いです。', kanji:'川',
      options:['かわ','うみ','いけ','みずうみ'], answer:0,
      explanation:'川（かわ）= river',
      explanationZh:'川 讀作 かわ，意思是「河川」。' },
    { id:'s1q1_3', sentence:'<u>水</u>を一杯ください。', kanji:'水',
      options:['みず','ゆ','あめ','こおり'], answer:0,
      explanation:'水（みず）= water',
      explanationZh:'水 讀作 みず，意思是「水」。' },
    { id:'s1q1_4', sentence:'<u>電車</u>で学校へ行きます。', kanji:'電車',
      options:['でんしゃ','でんき','じどうしゃ','ひこうき'], answer:0,
      explanation:'電車（でんしゃ）= train',
      explanationZh:'電車 讀作 でんしゃ，意思是「電車」。' },
    { id:'s1q1_5', sentence:'<u>先生</u>はとてもやさしいです。', kanji:'先生',
      options:['せんせい','がくせい','ともだち','かぞく'], answer:0,
      explanation:'先生（せんせい）= teacher',
      explanationZh:'先生 讀作 せんせい，意思是「老師」。' },
    { id:'s1q1_6', sentence:'今日は<u>月曜日</u>です。', kanji:'月曜日',
      options:['げつようび','かようび','すいようび','もくようび'], answer:0,
      explanation:'月曜日（げつようび）= Monday',
      explanationZh:'月曜日 讀作 げつようび，意思是「星期一」。' },
    { id:'s1q1_7', sentence:'<u>学校</u>は九時に始まります。', kanji:'学校',
      options:['がっこう','だいがく','びょういん','としょかん'], answer:0,
      explanation:'学校（がっこう）= school',
      explanationZh:'学校 讀作 がっこう，意思是「學校」。' },
    { id:'s1q1_8', sentence:'<u>右手</u>で書いてください。', kanji:'右手',
      options:['みぎて','ひだりて','うしろて','まえて'], answer:0,
      explanation:'右手（みぎて）= right hand',
      explanationZh:'右手 讀作 みぎて，意思是「右手」。' },
    { id:'s1q1_9', sentence:'毎日<u>食べ物</u>に気をつけています。', kanji:'食べ物',
      options:['たべもの','のみもの','つくりもの','うりもの'], answer:0,
      explanation:'食べ物（たべもの）= food',
      explanationZh:'食べ物 讀作 たべもの，意思是「食物」。' },
    { id:'s1q1_10', sentence:'あの<u>大きい</u>建物は何ですか。', kanji:'大きい',
      options:['おおきい','ちいさい','たかい','ひくい'], answer:0,
      explanation:'大きい（おおきい）= big/large',
      explanationZh:'大きい 讀作 おおきい，意思是「大的」。' },
  ],

  s1q2: [
    { id:'s1q2_1', sentence:'あの___は高いです。', hint:'やま',
      options:['山','川','海','森'], answer:0,
      explanation:'やま = 山 (mountain)',
      explanationZh:'やま 的漢字是 山，意思是「山」。' },
    { id:'s1q2_2', sentence:'___を一杯ください。', hint:'みず',
      options:['水','火','土','木'], answer:0,
      explanation:'みず = 水 (water)',
      explanationZh:'みず 的漢字是 水，意思是「水」。' },
    { id:'s1q2_3', sentence:'___を書いてください。', hint:'なまえ',
      options:['名前','電話','住所','番号'], answer:0,
      explanation:'なまえ = 名前 (name)',
      explanationZh:'なまえ 的漢字是 名前，意思是「名字」。' },
    { id:'s1q2_4', sentence:'___は楽しいです。', hint:'がっこう',
      options:['学校','病院','図書館','郵便局'], answer:0,
      explanation:'がっこう = 学校 (school)',
      explanationZh:'がっこう 的漢字是 学校，意思是「學校」。' },
    { id:'s1q2_5', sentence:'___が降っています。', hint:'あめ',
      options:['雨','雪','風','霧'], answer:0,
      explanation:'あめ = 雨 (rain)',
      explanationZh:'あめ 的漢字是 雨，意思是「雨」。' },
    { id:'s1q2_6', sentence:'部屋の___がつきません。', hint:'でんき',
      options:['電気','電話','電車','電池'], answer:0,
      explanation:'でんき = 電気 (electricity/light)',
      explanationZh:'でんき 的漢字是 電気，意思是「電燈/電氣」。' },
    { id:'s1q2_7', sentence:'___に住んでいます。', hint:'にほん',
      options:['日本','中国','韓国','台湾'], answer:0,
      explanation:'にほん = 日本 (Japan)',
      explanationZh:'にほん 的漢字是 日本，即「日本」。' },
    { id:'s1q2_8', sentence:'___勉強しています。', hint:'まいにち',
      options:['毎日','毎朝','毎週','毎月'], answer:0,
      explanation:'まいにち = 毎日 (every day)',
      explanationZh:'まいにち 的漢字是 毎日，意思是「每天」。' },
  ],

  s1q3: [
    { id:'s1q3_1', sentence:'毎朝、（　）を飲みます。',
      options:['コーヒー','教科書','電車','学校'], answer:0,
      explanation:'飲む（のむ）はドリンクと使う。コーヒーは飲み物。',
      explanationZh:'飲む（のむ）= 喝，搭配飲料。コーヒー（咖啡）是飲料，故選 A。' },
    { id:'s1q3_2', sentence:'お腹が（　）ので、何か食べたいです。',
      options:['すいた','いっぱいの','つかれた','ねむい'], answer:0,
      explanation:'お腹がすいた = hungry（空腹）',
      explanationZh:'お腹がすいた = 肚子餓了。因為餓，才想吃東西，故選 A。' },
    { id:'s1q3_3', sentence:'漢字の（　）を勉強しています。',
      options:['読み方','場所','時間','色'], answer:0,
      explanation:'読み方（よみかた）= how to read',
      explanationZh:'読み方（よみかた）= 讀法/讀音。漢字的讀法 → 漢字の読み方。' },
    { id:'s1q3_4', sentence:'寒いので、（　）を着ます。',
      options:['コート','サンダル','帽子','めがね'], answer:0,
      explanation:'寒い時はコートを着る。',
      explanationZh:'寒い（さむい）= 冷。天冷時穿コート（大衣），最合邏輯。' },
    { id:'s1q3_5', sentence:'この問題は（　）です。答えがわかりません。',
      options:['難しい','おいしい','たのしい','やさしい'], answer:0,
      explanation:'答えがわからない → 難しい（むずかしい）',
      explanationZh:'答えがわからない = 不知道答案，表示題目很難 → 難しい（むずかしい）。' },
    { id:'s1q3_6', sentence:'電話番号を（　）に書いてください。',
      options:['ノート','テレビ','電子レンジ','冷蔵庫'], answer:0,
      explanation:'書く（かく）はノートや紙にする。',
      explanationZh:'書く（かく）= 寫，寫字要用筆記本（ノート）或紙，故選 A。' },
    { id:'s1q3_7', sentence:'明日（　）があるので、今日は早く寝ます。',
      options:['テスト','テレビ','映画','料理'], answer:0,
      explanation:'テストがある前日は早く寝る。',
      explanationZh:'因為明天有テスト（考試），所以今天早點睡，邏輯最通順。' },
    { id:'s1q3_8', sentence:'（　）を見て、料理を作りました。',
      options:['レシピ','地図','時刻表','カレンダー'], answer:0,
      explanation:'料理はレシピを見て作る。',
      explanationZh:'做料理時看的是食譜（レシピ），故選 A。' },
  ],

  s1q4: [
    { id:'s1q4_1', sentence:'ちょっと待ってください。', underlined:'ちょっと',
      options:['すこし','たくさん','ずっと','もっと'], answer:0,
      explanation:'ちょっと ≈ すこし（a little）',
      explanationZh:'ちょっと ≈ すこし，都是「一點點」的意思。' },
    { id:'s1q4_2', sentence:'彼はとても親切な人です。', underlined:'親切な',
      options:['やさしい','きびしい','おかしい','むずかしい'], answer:0,
      explanation:'親切（しんせつ）≈ やさしい（kind）',
      explanationZh:'親切（しんせつ）≈ やさしい，都是「親切/和藹」的意思。' },
    { id:'s1q4_3', sentence:'もう一度言ってください。', underlined:'もう一度',
      options:['また','まず','まだ','もう'], answer:0,
      explanation:'もう一度 ≈ また（again）',
      explanationZh:'もう一度 ≈ また，都表示「再一次/再度」。' },
    { id:'s1q4_4', sentence:'お腹がいっぱいです。', underlined:'いっぱい',
      options:['たくさん入っている','少ない','空っぽ','少しある'], answer:0,
      explanation:'お腹がいっぱい = 食べ物がたくさん入っている状態',
      explanationZh:'お腹がいっぱい = 肚子飽了，即裡面「放了很多東西」（たくさん入っている）。' },
    { id:'s1q4_5', sentence:'この辺りはとてもにぎやかです。', underlined:'にぎやか',
      options:['元気で活発な','静かな','きれいな','古い'], answer:0,
      explanation:'にぎやか = 人が多くて活気がある（lively）',
      explanationZh:'にぎやか = 熱鬧，即人多、活力充沛（元気で活発な）的樣子。' },
    { id:'s1q4_6', sentence:'すぐに来てください。', underlined:'すぐ',
      options:['はやく','ゆっくり','あとで','たまに'], answer:0,
      explanation:'すぐ ≈ はやく（immediately/quickly）',
      explanationZh:'すぐ ≈ はやく，都表示「立刻/趕快」。' },
    { id:'s1q4_7', sentence:'この公園はとてもきれいです。', underlined:'きれい',
      options:['美しい','難しい','楽しい','怖い'], answer:0,
      explanation:'きれい ≈ 美しい（うつくしい）（beautiful）',
      explanationZh:'きれい ≈ 美しい（うつくしい），都是「漂亮/美麗」的意思。' },
    { id:'s1q4_8', sentence:'彼女はとても元気です。', underlined:'元気',
      options:['活発で健康な','静かな','悲しい','怒っている'], answer:0,
      explanation:'元気 = 活発で健康な様子（energetic/healthy）',
      explanationZh:'元気 = 精神好、活力充沛，即「活発で健康な」的樣子。' },
  ],

  // ── SECTION 2: 文法・読解 ─────────────────────────────────────────

  s2q1: [
    { id:'s2q1_1', sentence:'毎日図書館（　）勉強します。',
      options:['で','に','を','が'], answer:0,
      explanation:'で = 場所を表す助詞（行為が行われる場所）。図書館で勉強する。',
      explanationZh:'で = 表示行為發生的地點（in/at）。在圖書館念書 → 図書館で。' },
    { id:'s2q1_2', sentence:'友達（　）プレゼントをもらいました。',
      options:['から','に','で','を'], answer:0,
      explanation:'から = 起点（from）。友達からもらう。',
      explanationZh:'から = 表示來源（from）。從朋友那裡收到 → 友達から。' },
    { id:'s2q1_3', sentence:'電車（　）乗って、学校へ行きます。',
      options:['に','を','で','が'], answer:0,
      explanation:'電車に乗る（のる）= to ride the train。乗る は に を使う。',
      explanationZh:'乗る（のる）= 搭乘，必搭助詞 に。電車に乗る = 搭電車。' },
    { id:'s2q1_4', sentence:'新しいかばん（　）買いたいです。',
      options:['を','に','が','は'], answer:0,
      explanation:'を = 直接目的語。かばんを買う。',
      explanationZh:'を = 直接受詞助詞。買（かう）的對象 → かばんを。' },
    { id:'s2q1_5', sentence:'テーブルの上（　）本があります。',
      options:['に','で','を','が'], answer:0,
      explanation:'に = 存在を表す場所。〜の上に〜がある。',
      explanationZh:'に = 表示存在的地點。〜の上に〜がある（某處有某物）。' },
    { id:'s2q1_6', sentence:'東京（　）大阪まで新幹線で行きます。',
      options:['から','に','を','まで'], answer:0,
      explanation:'から〜まで = from〜to。東京から大阪まで。',
      explanationZh:'から〜まで = 從〜到〜。東京から大阪まで = 從東京到大阪。' },
    { id:'s2q1_7', sentence:'この料理（　）作り方を教えてください。',
      options:['の','に','を','が'], answer:0,
      explanation:'の = 修飾（modification）。この料理の作り方。',
      explanationZh:'の = 所有格/修飾。「この料理の作り方」= 這道料理的做法。' },
    { id:'s2q1_8', sentence:'日本語（　）話すのが好きです。',
      options:['を','が','に','で'], answer:0,
      explanation:'を = 行為の対象。日本語を話す。',
      explanationZh:'を = 動作的對象。話す（はなす）的對象 → 日本語を。' },
    { id:'s2q1_9', sentence:'明日の会議に間に合う（　）、今から急ぎます。',
      options:['ために','ので','から','けど'], answer:0,
      explanation:'ために = in order to。〜ために〜する。',
      explanationZh:'ために = 為了〜（表示目的）。為了趕上明天的會議，所以現在趕快。' },
    { id:'s2q1_10', sentence:'もっとゆっくり話して（　）ですか。',
      options:['もらえません','もらいます','いきます','います'], answer:0,
      explanation:'〜てもらえませんか = Could you please〜? 依頼の表現。',
      explanationZh:'〜てもらえませんか = 能請您幫我〜嗎？禮貌的請求表現。' },
  ],

  s2q2: [
    { id:'s2q2_1',
      before:'田中さんは', after:'います。',
      words:['読んで','図書館で','本を','今'],
      correctOrder:[3,1,2,0], starSlot:2, answer:2,
      fullSentence:'田中さんは今図書館で本を読んでいます。',
      explanation:'今（時）→ 図書館で（場所）→ 本を（目的語）→ 読んで',
      explanationZh:'語序：今（時間）→ 図書館で（地點）→ 本を（受詞）→ 読んで（動詞）。★第3格 = 本を。' },
    { id:'s2q2_2',
      before:'昨日', after:'食べました。',
      words:['を','家族と','レストランで','すし'],
      correctOrder:[1,2,3,0], starSlot:2, answer:3,
      fullSentence:'昨日家族とレストランですしを食べました。',
      explanation:'家族と（一緒に）→ レストランで（場所）→ すしを（目的語）',
      explanationZh:'語序：家族と（一起）→ レストランで（地點）→ すし（受詞）→ を。★第3格 = すし。' },
    { id:'s2q2_3',
      before:'あの', after:'おいしいです。',
      words:['は','料理','レストランの','とても'],
      correctOrder:[2,1,0,3], starSlot:2, answer:0,
      fullSentence:'あのレストランの料理はとてもおいしいです。',
      explanation:'レストランの（修飾）→ 料理（主語）→ は（助詞）→ とても（副詞）',
      explanationZh:'語序：レストランの（修飾）→ 料理（主語）→ は（助詞）→ とても（副詞）。★第3格 = は。' },
    { id:'s2q2_4',
      before:'将来、私は', after:'たいです。',
      words:['に','先生','なり','学校の'],
      correctOrder:[3,1,0,2], starSlot:2, answer:0,
      fullSentence:'将来、私は学校の先生になりたいです。',
      explanation:'学校の先生（修飾+名詞）→ に（〜になる）→ なり（動詞）',
      explanationZh:'「〜になる」= 成為〜，助詞固定用 に。語序：学校の先生 → に → なり。★第3格 = に。' },
    { id:'s2q2_5',
      before:'妹は', after:'います。',
      words:['勉強して','一人で','今','部屋で'],
      correctOrder:[2,3,1,0], starSlot:2, answer:1,
      fullSentence:'妹は今部屋で一人で勉強しています。',
      explanation:'今（時）→ 部屋で（場所）→ 一人で（様態）→ 勉強して',
      explanationZh:'語序：今（時間）→ 部屋で（地點）→ 一人で（方式）→ 勉強して。★第3格 = 一人で。' },
  ],

  s2q3: [
    { id:'s2q3_a', type:'grammar_passage', title:'パッセージ A',
      passage:'私は学生です。毎朝六時（①）起きます。そして、顔を洗ってから、朝ごはん（②）食べます。学校（③）八時に着きます。',
      blanks:[
        { label:'①', options:['に','で','を','が'], answer:0,
          explanation:'六時に起きる（時刻 + に）',
          explanationZh:'時刻 + に = 表示動作發生的時間點。六時に起きる = 六點起床。' },
        { label:'②', options:['を','に','が','は'], answer:0,
          explanation:'朝ごはんを食べる（目的語 + を）',
          explanationZh:'食べる（たべる）的受詞用 を。朝ごはんを食べる = 吃早餐。' },
        { label:'③', options:['に','で','を','と'], answer:0,
          explanation:'学校に着く（到達点 + に）',
          explanationZh:'着く（つく）= 到達，必搭助詞 に。学校に着く = 到達學校。' },
      ]
    },
    { id:'s2q3_b', type:'grammar_passage', title:'パッセージ B',
      passage:'田中さんはスーパー（①）買い物をします。野菜（②）果物を買います。今日（③）天気がいいので、歩いて帰ります。',
      blanks:[
        { label:'①', options:['で','に','を','が'], answer:0,
          explanation:'スーパーで買い物する（行為の場所 + で）',
          explanationZh:'で = 行為發生的地點。在超市買東西 → スーパーで。' },
        { label:'②', options:['と','や','の','も'], answer:0,
          explanation:'野菜と果物（and）→ と',
          explanationZh:'と = 並列（and），野菜と果物 = 蔬菜和水果。' },
        { label:'③', options:['は','が','を','に'], answer:0,
          explanation:'今日は（話題の提示 + は）',
          explanationZh:'は = 提示話題。今日は天気がいい = 今天天氣好（強調今天）。' },
      ]
    },
  ],

  s2q4: [
    { id:'s2q4_a', type:'reading_short',
      passage:'田中さんは毎日電車で会社に行きます。家から会社まで40分かかります。田中さんは毎朝7時に家を出て、7時40分に会社に着きます。',
      questions:[
        { q:'田中さんはどうやって会社へ行きますか。',
          options:['車で','電車で','バスで','歩いて'], answer:1,
          explanation:'「毎日電車で会社に行きます」とあります。',
          explanationZh:'文章說「毎日電車で会社に行きます」，故選 B 電車で。' },
        { q:'田中さんが会社に着くのは何時ですか。',
          options:['7時','7時20分','7時40分','8時'], answer:2,
          explanation:'「7時40分に会社に着きます」とあります。',
          explanationZh:'文章說「7時40分に会社に着きます」，故選 C 7時40分。' },
      ]
    },
    { id:'s2q4_b', type:'reading_short',
      passage:'山田先生は日本語を教えています。先生の授業はおもしろくて、学生たちはみんな好きです。先生はやさしくて、わからないことがあると、丁寧に説明してくれます。',
      questions:[
        { q:'山田先生は何をしていますか。',
          options:['日本語を勉強している','日本語を教えている','学校へ行っている','授業を受けている'], answer:1,
          explanation:'「山田先生は日本語を教えています」とあります。',
          explanationZh:'文章開頭說「山田先生は日本語を教えています」，故選 B。' },
        { q:'学生たちはなぜ先生の授業が好きですか。',
          options:['難しいから','短いから','おもしろいから','静かだから'], answer:2,
          explanation:'「授業はおもしろくて、学生たちはみんな好きです」とあります。',
          explanationZh:'文章說「授業はおもしろくて、学生たちはみんな好きです」，故選 C おもしろいから。' },
      ]
    },
  ],

  s2q5: [
    { id:'s2q5_a', type:'reading_medium',
      passage:'私の趣味は料理です。週末になると、新しいレシピを試してみます。先週は日本食を作りました。まず、材料を買いに近くのスーパーへ行きました。スーパーでは新鮮な野菜と魚を買いました。家に帰ってから、料理を始めました。二時間かかりましたが、とてもおいしい料理ができました。家族みんながおいしいと言ってくれたので、とても嬉しかったです。次は別の国の料理に挑戦したいと思っています。',
      questions:[
        { q:'この人の趣味は何ですか。',
          options:['映画を見ること','料理をすること','旅行をすること','買い物をすること'], answer:1,
          explanation:'「私の趣味は料理です」とあります。',
          explanationZh:'文章第一句「私の趣味は料理です」，故選 B 料理をすること。' },
        { q:'先週、この人は何を作りましたか。',
          options:['中国料理','フランス料理','日本食','イタリア料理'], answer:2,
          explanation:'「先週は日本食を作りました」とあります。',
          explanationZh:'文章說「先週は日本食を作りました」，故選 C 日本食。' },
        { q:'料理を作るのにどのくらいかかりましたか。',
          options:['30分','1時間','2時間','3時間'], answer:2,
          explanation:'「二時間かかりましたが」とあります。',
          explanationZh:'文章說「二時間かかりましたが」，故選 C 2時間。' },
      ]
    },
  ],

  s2q6: [
    { id:'s2q6_a', type:'info_retrieval',
      title:'日本語教室のお知らせ',
      passage:`【日本語教室のお知らせ】

日時：毎週火曜日と木曜日
　　　午後7時〜午後9時

場所：市民センター3階 301号室

対象：日本語を勉強したい方

受講料：月4,000円（テキスト代は別途）

申し込み：電話またはメールで受け付けます

問い合わせ：市民センター（電話 03-1234-5678）`,
      questions:[
        { q:'この日本語教室はいつありますか。',
          options:['月曜日と水曜日','火曜日と木曜日','月曜日から金曜日','土曜日と日曜日'], answer:1,
          explanation:'「毎週火曜日と木曜日」とあります。',
          explanationZh:'公告中寫「毎週火曜日と木曜日」，故選 B 火曜日と木曜日。' },
        { q:'受講料はいくらですか。',
          options:['月2,000円','月3,000円','月4,000円','月5,000円'], answer:2,
          explanation:'「受講料：月4,000円」とあります。',
          explanationZh:'公告中寫「受講料：月4,000円」，故選 C 月4,000円。' },
      ]
    },
  ],

  // ── SECTION 3: 聴解 ────────────────────────────────────────────────

  s3q1: [
    { id:'s3q1_1',
      situation:'男の人が店でシャツを買おうとしています。',
      script:`店員：いらっしゃいませ。
男性：すみません、このシャツのMサイズはありますか。
店員：ただ今お調べします。少々お待ちください。……申し訳ございません、Mサイズは只今切れております。Lサイズならございますが。
男性：じゃあ、Lサイズをください。
店員：3,500円になります。`,
      question:'男性はどうしますか。',
      options:['Mサイズのシャツを買う','Lサイズのシャツを買う','シャツを買わない','別の店へ行く'], answer:1,
      explanation:'「Lサイズをください」と言ったので、Lサイズを買います。',
      explanationZh:'男性說「Lサイズをください」，故選 B Lサイズのシャツを買う。' },
    { id:'s3q1_2',
      situation:'友達と待ち合わせの話をしています。',
      script:`女性：もしもし、田中さん？今どこにいますか。
男性：駅の改札の前にいます。
女性：あ、私は今コンビニの前にいます。あと3分で行きます。
男性：わかりました。じゃあ、ここで待っています。`,
      question:'女性はこれからどうしますか。',
      options:['男性のいるところへ行く','コンビニで買い物をする','電話を切る','家に帰る'], answer:0,
      explanation:'「あと3分で行きます」と言ったので、男性のいる駅の改札前へ行きます。',
      explanationZh:'女性說「あと3分で行きます」，要去男性所在的地方，故選 A。' },
    { id:'s3q1_3',
      situation:'レストランで注文をしています。',
      script:`客：すみません、このランチセットに飲み物はついていますか。
店員：はい、コーヒーか紅茶をお選びいただけます。
客：じゃあ、コーヒーをください。砂糖はいりません。ミルクだけお願いします。
店員：かしこまりました。`,
      question:'客はどのようにコーヒーを飲みますか。',
      options:['砂糖もミルクも入れる','砂糖だけ入れる','ミルクだけ入れる','何も入れない'], answer:2,
      explanation:'「砂糖はいりません。ミルクだけお願いします」とあります。',
      explanationZh:'客人說「砂糖はいりません。ミルクだけお願いします」，故選 C ミルクだけ入れる。' },
    { id:'s3q1_4',
      situation:'病院の受付で話をしています。',
      script:`受付：初めていらっしゃいますか。
患者：はい、初めてです。
受付：では、まずこちらの用紙にお名前と住所と電話番号をご記入ください。それから保険証を見せてください。
患者：はい、わかりました。`,
      question:'患者はまず何をしますか。',
      options:['名前・住所・電話番号を書く','保険証を出す','お金を払う','診察を受ける'], answer:0,
      explanation:'「まずこちらの用紙にお名前と住所と電話番号をご記入ください」とあります。',
      explanationZh:'受付說「まずこちらの用紙に…ご記入ください」，まず（首先）要先填表，故選 A。' },
    { id:'s3q1_5',
      situation:'授業の後で先生と話しています。',
      script:`学生：先生、明日の宿題についてお聞きしてもいいですか。
先生：はい、どうぞ。
学生：5ページから10ページまで読んで質問に答えるんですよね。
先生：そうです。それから、わからない言葉を辞書で調べて、ノートに書いてきてください。
学生：はい、わかりました。`,
      question:'学生の宿題はどれですか。',
      options:['5〜10ページを読む','読んで質問に答える','読んで質問に答えて、わからない言葉を調べる','ノートに漢字を書く'], answer:2,
      explanation:'読む＋質問に答える＋わからない言葉を調べてノートに書く、の三つです。',
      explanationZh:'作業共三項：①閱讀5〜10頁、②回答問題、③查不懂的詞語並記在筆記本，故選 C。' },
  ],

  s3q2: [
    { id:'s3q2_1', situation:'学校のお知らせを聞いています。',
      script:'明日の運動会は雨が降るかもしれないので、もし雨なら体育館で行います。晴れなら予定通りグラウンドで行います。',
      question:'晴れの場合、明日の運動会はどこで行いますか。',
      options:['体育館','グラウンド','教室','公園'], answer:1,
      explanation:'「晴れなら予定通りグラウンドで行います」とあります。',
      explanationZh:'「晴れなら予定通りグラウンドで行います」，晴天在グラウンド，故選 B。' },
    { id:'s3q2_2', situation:'スーパーのアナウンスを聞いています。',
      script:'このスーパーでは、今月いっぱい野菜が半額です。ただし、お一人様5袋までとなっています。ポイントカードをお持ちのお客様は、さらに10%引きになります。',
      question:'野菜はいつ半額ですか。',
      options:['いつでも半額','今週だけ','今月だけ','来月から'], answer:2,
      explanation:'「今月いっぱい野菜が半額です」とあります。',
      explanationZh:'「今月いっぱい野菜が半額」，只有本月打折，故選 C 今月だけ。' },
    { id:'s3q2_3', situation:'公園でアナウンスを聞いています。',
      script:'本日のイベントのお知らせです。午後2時から噴水広場でコンサートが行われます。参加は無料ですが、座席に限りがありますので、お早めにお越しください。',
      question:'コンサートについて正しいのはどれですか。',
      options:['午前中に行われる','お金がかかる','座席は先着順','申し込みが必要'], answer:2,
      explanation:'座席に限りがあり、早く来た人から座れます（先着順）。参加は無料。',
      explanationZh:'「座席に限りがある、お早めに」= 座位有限、先到先得（先著順）。參加免費，故選 C。' },
    { id:'s3q2_4', situation:'メッセージを聞いています。',
      script:'田中さん、明日の会議は午前10時から始まります。場所は本社3階の会議室です。資料は前日までにメールで送ってください。よろしくお願いします。',
      question:'資料はいつ送りますか。',
      options:['会議の当日','会議の前日まで','会議が終わった後','今日中'], answer:1,
      explanation:'「資料は前日までにメールで送ってください」とあります。',
      explanationZh:'「資料は前日までにメールで送ってください」= 前一天之前寄送，故選 B。' },
    { id:'s3q2_5', situation:'電車のアナウンスを聞いています。',
      script:'次の電車は3番線から発車します。2番線の電車は工事のため、今日は運休いたします。ご不便をおかけして申し訳ありません。',
      question:'今日、2番線はどうなりますか。',
      options:['普通に運転している','工事のため運休','3番線に変更','遅れている'], answer:1,
      explanation:'「2番線の電車は工事のため、今日は運休いたします」とあります。',
      explanationZh:'「2番線の電車は工事のため、今日は運休」= 今天2號月台因施工停駛，故選 B。' },
  ],

  s3q3: [
    { id:'s3q3_1', situation:'あなたはクラスメートに鉛筆を借りたいです。何と言いますか。', image:'✏️',
      options:['「鉛筆を使ってもいいですよ。」','「鉛筆を貸してもらえませんか。」','「鉛筆がありますよ。」','「鉛筆を使いましたよ。」'], answer:1,
      explanation:'〜てもらえませんか = Could you〜? 相手に何かをお願いする丁寧な表現。',
      explanationZh:'〜てもらえませんか = 能幫我〜嗎？向對方提出請求的禮貌說法，故選 B。' },
    { id:'s3q3_2', situation:'道で知らない人に今の時間を聞きたいです。何と言いますか。', image:'⏰',
      options:['「今何時か知っていますか。」','「すみません、今何時ですか。」','「時計はどこですか。」','「時間がありますか。」'], answer:1,
      explanation:'見知らぬ人に声をかけるときは「すみません」+ 質問が自然です。',
      explanationZh:'向陌生人問路，先說「すみません」（不好意思）再問，是最自然的說法，故選 B。' },
    { id:'s3q3_3', situation:'友達に誕生日プレゼントをもらいました。何と言いますか。', image:'🎁',
      options:['「どういたしまして。」','「申し訳ありません。」','「ありがとうございます。」','「よろしくお願いします。」'], answer:2,
      explanation:'プレゼントをもらったとき → ありがとうございます（Thank you）',
      explanationZh:'收到禮物時應說「ありがとうございます」（謝謝），故選 C。' },
    { id:'s3q3_4', situation:'レストランで食事が終わり、お会計をお願いしたいです。何と言いますか。', image:'🍽️',
      options:['「すみません、お水ください。」','「すみません、お会計お願いします。」','「すみません、メニューをください。」','「すみません、席はありますか。」'], answer:1,
      explanation:'「お会計お願いします」= Please bring the check / I\'d like to pay.',
      explanationZh:'「お会計お願いします」= 請結帳，是餐廳付款時的標準說法，故選 B。' },
    { id:'s3q3_5', situation:'先生の部屋に入る前に何と言いますか。', image:'🚪',
      options:['「さようなら。」','「おはようございます。」','「失礼します。」','「お疲れ様です。」'], answer:2,
      explanation:'部屋に入るとき → 「失礼します」（しつれいします）= Excuse me for entering.',
      explanationZh:'進入別人房間前說「失礼します」（しつれいします）= 打擾了，故選 C。' },
  ],

  s3q4: [
    { id:'s3q4_1', prompt:'「今日の天気はどうですか。」',
      options:['「はい、いいです。」','「今日は晴れています。」','「天気が好きです。」','「明日は雨です。」'], answer:1,
      explanation:'天気の様子を答えます。「晴れています」が適切。',
      explanationZh:'問天氣狀況，應回答天氣狀態「今日は晴れています」（今天是晴天），故選 B。' },
    { id:'s3q4_2', prompt:'「日本語を勉強しているんですか。」',
      options:['「はい、毎日勉強しています。」','「いいえ、日本語が好きです。」','「はい、学校に行きます。」','「いいえ、難しくないです。」'], answer:0,
      explanation:'「〜しているんですか」という確認問句に、「〜しています」で答えます。',
      explanationZh:'「〜しているんですか」是確認問句，用「はい、〜しています」直接回答，故選 A。' },
    { id:'s3q4_3', prompt:'「この近くに銀行はありますか。」',
      options:['「銀行でお金を引き出しました。」','「はい、あそこに大きい銀行がありますよ。」','「私は銀行員です。」','「銀行は9時に開きます。」'], answer:1,
      explanation:'「ありますか」という質問に「ありますよ」と場所を教えます。',
      explanationZh:'「ありますか」= 有嗎？正確回答是「はい、あそこにあります」（有，在那裡），故選 B。' },
    { id:'s3q4_4', prompt:'「もう昼ごはんを食べましたか。」',
      options:['「昼ごはんが好きです。」','「はい、さっき食べました。」','「昼ごはんは12時です。」','「食べましょう。」'], answer:1,
      explanation:'「食べましたか」という完了の質問に「食べました」で答えます。',
      explanationZh:'「食べましたか」= 吃了嗎？用「はい、さっき食べました」（是的，剛才吃了）回答，故選 B。' },
    { id:'s3q4_5', prompt:'「どこの出身ですか。」',
      options:['「台湾が好きです。」','「台湾から来ました。」','「台湾は遠いです。」','「台湾語を話します。」'], answer:1,
      explanation:'出身を聞かれたら「〜から来ました」と答えます。',
      explanationZh:'「どこの出身ですか」= 你是哪裡人？用「〜から来ました」（我從〜來）回答，故選 B。' },
    { id:'s3q4_6', prompt:'「週末は何をしましたか。」',
      options:['「週末が好きです。」','「友達と映画を見ました。」','「明日も休みです。」','「週末はいつも忙しいです。」'], answer:1,
      explanation:'「何をしましたか」という過去の質問に、過去形で活動を答えます。',
      explanationZh:'「何をしましたか」= 做了什麼？用過去式「〜しました」具體回答活動，故選 B。' },
  ],
};

// ── Mock test config ───────────────────────────────────────────────────────
const MOCK_TEST = {
  section1: {
    titleKey:'label_s1', time:20*60,
    groups:[
      { labelKey:'label_s1q1', type:'kanji_reading',  data:QB.s1q1.slice(0,5) },
      { labelKey:'label_s1q2', type:'kanji_writing',  data:QB.s1q2.slice(0,4) },
      { labelKey:'label_s1q3', type:'context_vocab',  data:QB.s1q3.slice(0,6) },
      { labelKey:'label_s1q4', type:'synonym',        data:QB.s1q4.slice(0,4) },
    ]
  },
  section2: {
    titleKey:'label_s2', time:40*60,
    groups:[
      { labelKey:'label_s2q1', type:'grammar_particle', data:QB.s2q1.slice(0,8) },
      { labelKey:'label_s2q2', type:'grammar_ordering', data:QB.s2q2 },
      { labelKey:'label_s2q3', type:'grammar_passage',  data:QB.s2q3 },
      { labelKey:'label_s2q4', type:'reading_short',    data:QB.s2q4 },
      { labelKey:'label_s2q5', type:'reading_medium',   data:QB.s2q5 },
      { labelKey:'label_s2q6', type:'info_retrieval',   data:QB.s2q6 },
    ]
  },
  section3: {
    titleKey:'label_s3', time:30*60,
    groups:[
      { labelKey:'label_s3q1', type:'listening_task',          data:QB.s3q1 },
      { labelKey:'label_s3q2', type:'listening_keypoint',      data:QB.s3q2 },
      { labelKey:'label_s3q3', type:'listening_expression',    data:QB.s3q3 },
      { labelKey:'label_s3q4', type:'listening_quickresponse', data:QB.s3q4 },
    ]
  },
};

// ── Practice menu ──────────────────────────────────────────────────────────
const PRACTICE_MENU = [
  { section:1, titleKey:'label_s1', items:[
    { labelKey:'label_s1q1', type:'kanji_reading',   data:QB.s1q1 },
    { labelKey:'label_s1q2', type:'kanji_writing',   data:QB.s1q2 },
    { labelKey:'label_s1q3', type:'context_vocab',   data:QB.s1q3 },
    { labelKey:'label_s1q4', type:'synonym',         data:QB.s1q4 },
  ]},
  { section:2, titleKey:'label_s2', items:[
    { labelKey:'label_s2q1', type:'grammar_particle',  data:QB.s2q1 },
    { labelKey:'label_s2q2', type:'grammar_ordering',  data:QB.s2q2 },
    { labelKey:'label_s2q3', type:'grammar_passage',   data:QB.s2q3 },
    { labelKey:'label_s2q4', type:'reading_short',     data:QB.s2q4 },
    { labelKey:'label_s2q5', type:'reading_medium',    data:QB.s2q5 },
    { labelKey:'label_s2q6', type:'info_retrieval',    data:QB.s2q6 },
  ]},
  { section:3, titleKey:'label_s3', items:[
    { labelKey:'label_s3q1', type:'listening_task',          data:QB.s3q1 },
    { labelKey:'label_s3q2', type:'listening_keypoint',      data:QB.s3q2 },
    { labelKey:'label_s3q3', type:'listening_expression',    data:QB.s3q3 },
    { labelKey:'label_s3q4', type:'listening_quickresponse', data:QB.s3q4 },
  ]},
];
